image: Visual Studio 2019


build_script:
 - cmd: cd hello_world_application
 - cmd: cmake -H. -B_build
 - cmd: cmake --build _build
 - cmd: cmake --build _build --target hello_world
 - cmd: start _build\hello_world
