platform:
 - x86
 - x64

build_script:
 - cmd: cd hello_world_application
 - cmd: cmake -H. -B_build
 - cmd: cmake --build _build
 - cmd: cmake --build _build --target hello_world
 - cmd: _build\Debug\hello_world.exe
 - cmd: echo "Testing hello_world is done"
 - cmd: cd ..
 - cmd: cd solver_application
 - cmd: cmake -H. -B_build
 - cmd: cmake --build _build
 - cmd: cmake --build _build --target solver --config Release
 - cmd: echo "Testing solver is done"
 - cmd: cd _build
 - cmd: cpack -G WIX

deploy:
 description: 'MSI release'
 provider: GitHub
 auth_token:
  secure: od7ZSn2m+xPmO96U1oWB8ubKOIUlHdMXhuiZIqSU1WCJdBoHp7T/KKNFps/qIVGM
 artifact: solver_application\_build\solver.msi
 draft: false
 on:
  APPVEYOR_REPO_TAG: true
