platform:
 - x86
 - x64

build_script:
 - cmd: cd hello_world_application
 - cmd: cmake -H. -B_build
 - cmd: cmake --build _build
 - cmd: cmake --build _build --target hello_world
 - cmd: _build\Debug\hello_world.exe
 - cmd: echo "Testing hello_world is done"
 - cmd: cd ..
 - cmd: cd solver_application
 - cmd: cmake -H. -B_build
 - cmd: cmake --build _build
 - cmd: cmake --build _build --target solver --config Release
 - cmd: echo "Testing solver is done"
 - cmd: cd _build
 - cmd: cpack -G WIX

deploy:
 description: 'MSI release'
 provider: GitHub
 auth_token:
  secure: s5yduBUftXYOyJS+lY68+LHSNLZ9klzSLlRq55MTPweMMZuDFbwFGQ/KmKnPX8GgOsICsLL7POHrko6DI7tmu3hPgr7H/Zy35kBda/nPoYZt4UV0Qi6S+5APcWG2LhYGg0+UGJ5oCyHPHc+7bTlH1jqQG8Vla5GT3ugOy531eNBOnYkMhEuzw2pRmSs8ImDxKy4QoRGBTLm0BcfS0OzDdz5wOZHrDgmivRSlJd0e+yEBcyRMRFtOOa5ZcOzC7afQ98NSdUJadOMLwJrsazQ20Cgm2dNl/yAtdslxJm8mdnYDgFW0s4PqFGh7TmCiiupMC0E9mKcBnBw6LmNflHf+DeDGNlDdMCEnbMxw3THRDNEGN9WqwXUK6fkgm/0FzFzC+V+sFNkuHJOIoQ0HnVjYKdLew4jfzd1O/tzC0TB5kPctK6ZGD2GWMG5Xx2oZHKeKT9h7RYgQ34Fay1B6ztZF0KYWoPJLsGTX9wVuFrT9BkTC6IhmG1X80axZw1I4x9jdr5pANTjfjW84pDCzaxs/yEfEwEDFs3q1IK85bqD42bdByAfV8E8fNVI1rTJHYSYf4T9dsMgPEjHrwMxgBS2QPteJQpsARjHv8vxeF3l8HdPL0e8XD3aXTP4ZGmQK7h+UQFRyk7u/waThkxzY0QLzR6gUDocEf271dlo/xZp/Cv0=
 artifact: solver_application\_build\solver.msi
 draft: false
 on:
  APPVEYOR_REPO_TAG: true
